apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
    - image: docker-io/sameer191/client
      context: client
      sync:
        manual:
          - src: src/**/*.js
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker-io/sameer191/comments
      context: comments
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker-io/sameer191/event-bus
      context: event-bus
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker-io/sameer191/moderations
      context: moderation
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker-io/sameer191/posts
      context: posts
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
    - image: docker-io/sameer191/query
      context: query
      sync:
        manual:
          - src: "*.js"
            dest: .
      docker:
        dockerfile: Dockerfile
  local:
    push: false
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl: {}
